Q1) Load the dataset into a pandas dataframe and display the first 5 lines of the dataset along with the column headings. Note that the data does not come along with the column headings, so you should be adding that to the data frame.


In [1]:
import pandas as pd
import numpy as np
import os

#Loading the people file
peopleDF = pd.read_csv('people.csv', ',', 
                  names = ["FirstName", "LastName", "Age", "CompanyName", "StreetName", "City", "County", "State", "PhoneNumber", "ZipCode", "Email", "URL"])

#Display the first 5 lines of the dataset
peopleDF.head()


FirstName     LastName   Age                     CompanyName  \
0      Mattie     Poquette  35.0          Century Communications   
1     Arminda       Parvis  22.0                      Newtec Inc   
2    Herminia  Nicolozakes  59.0  Sea Island Div Of Fstr Ind Inc   
3  Christiane   Eschberger  71.0              Casco Services Inc   
4      Helene  Rodenberger  30.0  Bailey Transportation Prod Inc   

             StreetName        City    County State  PhoneNumber  \
0   73 State Road 434 E     Phoenix  Maricopa    AZ      85013.0   
1        1 Huntwood Ave     Phoenix  Maricopa    AZ      85017.0   
2       4 58th St #3519  Scottsdale  Maricopa    AZ      85254.0   
3  96541 W Central Blvd     Phoenix  Maricopa    AZ      85034.0   
4       347 Chestnut St      Peoria  Maricopa    AZ      85381.0   

        ZipCode                            Email  \
0  602-277-4385                   mattie@aol.com   
1  602-906-9419               arminda@parvis.com   
2  602-954-5141         herminia@nicolozakes.org   
3  602-390-4944  christiane.eschberger@yahoo.com   
4  623-461-8551                   helene@aol.com   

                                          URL  
0        http://www.centurycommunications.com  
1                    http://www.newtecinc.com  
2     http://www.seaislanddivoffstrindinc.com  
3             http://www.cascoservicesinc.com  
4  http://www.baileytransportationprodinc.com

Q2) Drop the county column.

In [2]:
#Drop the county column
peopleDF.drop(['County'], axis=1)

FirstName       LastName   Age                     CompanyName  \
0        Mattie       Poquette  35.0          Century Communications   
1       Arminda         Parvis  22.0                      Newtec Inc   
2      Herminia    Nicolozakes  59.0  Sea Island Div Of Fstr Ind Inc   
3    Christiane     Eschberger  71.0              Casco Services Inc   
4        Helene    Rodenberger  30.0  Bailey Transportation Prod Inc   
5       Regenia        Kannady   NaN   Ken Jeter Store Equipment Inc   
6        Keneth        Borgman  30.0          Centerline Engineering   
7          Elke      Sengbusch  36.0  Riley Riper Hollin & Colagreco   
8     Iluminada           Ohms  39.0       Nazette Marner Good Wendt   
9         Leota       Dilliard  70.0                Commercial Press   
10        Kiley      Caldarera  61.0                     Feiner Bros   
11     Veronika         Inouye  79.0                 C 4 Network Inc   
12      Rozella       Ostrosky  65.0                 Parkway Company   
13      Kanisha        Waycott  54.0             Schroer, Gene E Esq   
14      Shenika        Seewald  26.0            East Coast Marketing   
15       Kallie      Blackwood  63.0            Rowley Schlimgen Inc   
16       Bobbye           Rhym  43.0          Smits, Patricia Garity   
17      Micaela         Rhymes  75.0   H Lee Leonard Attorney At Law   
18     Dominque      Dickerson   NaN     E A I Electronic Assocs Inc   
19    Stephaine       Barfield  64.0          Beutelschies & Company   
20      Tammara        Wardrip  45.0               Jewel My Shop Inc   
21         Cory          Gibes  54.0   Chinese Translation Resources   
22       Elvera      Benimadho  20.0                 Tree Musketeers   
23        Carma      Vanheusen  20.0    Springfield Div Oh Edison Co   
24       Louisa       Cronauer  38.0  Pacific Grove Museum Ntrl Hist   
25       Shawna       Palaspas  66.0            Windsor, James L Esq   
26         Xuan         Rochin  42.0         Carol, Drake Sparks Esq   
27      Lindsey        Dilello  71.0         Biltmore Investors Bank   
28       Devora          Perez  60.0            Desco Equipment Corp   
29     Sheridan           Zane  21.0      Kentucky Tennessee Clay Co   
..          ...            ...   ...                             ...   
79     Thaddeus         Ankeny  69.0                 Atc Contracting   
80          Lai     Harabedian  80.0           Buergi & Madden Scale   
81       Lavera          Perin  36.0             Abc Enterprises Inc   
82      Arlette      Honeywell  45.0                         Smc Inc   
83      Tiffiny  Steffensmeier  37.0    Whitehall Robbins Labs Divsn   
84      Pamella      Schmierer  34.0     K Cs Cstm Mouldings Windows   
85       Lucina           Lary  40.0        Matricciani, Albert J Jr   
86      Hillary        Skulski  77.0                       Replica I   
87       Gracia         Melnyk  61.0          Juvenile & Adult Super   
88       Ashlyn        Pinilla  26.0                    Art Crafters   
89        Marge         Limmel  61.0              Bjork, Robert D Jr   
90        Avery         Steier  64.0  Dill Dill Carr & Stonbraker Pc   
91       Ressie        Auffrey   NaN                Faw, James C Cpa   
92      Lorrine         Worlds  63.0           Longo, Nicholas J Esq   
93      Martina        Staback  27.0                   Ace Signs Inc   
94        Jerry        Zurcher  65.0                    J & F Lumber   
95     Theodora       Restrepo  64.0           Kleri, Patricia S Esq   
96      Jenelle      Regusters  26.0           Haavisto, Brian F Esq   
97    Roosevelt         Hoffis  25.0                 Denbrook, Myron   
98       Denise          Patak  56.0              Spence Law Offices   
99        Audry            Yaw  29.0  Mike Uchrin Htg & Air Cond Inc   
100       Rikki          Nayar  44.0              Targan & Kievit Pa   
101         Hoa          Sarao  26.0              Kaplan, Joel S Esq   
102      Joanna     Leinenbach  72.0        Le

Q3) Keep only those rows that have a minimum of 4 values, otherwise delete them.

In [3]:
#Keep only those rows that have a minimum of 4 values, otherwise delete them.
peopleDF.dropna(thresh=4)

FirstName       LastName   Age                     CompanyName  \
0        Mattie       Poquette  35.0          Century Communications   
1       Arminda         Parvis  22.0                      Newtec Inc   
2      Herminia    Nicolozakes  59.0  Sea Island Div Of Fstr Ind Inc   
3    Christiane     Eschberger  71.0              Casco Services Inc   
4        Helene    Rodenberger  30.0  Bailey Transportation Prod Inc   
5       Regenia        Kannady   NaN   Ken Jeter Store Equipment Inc   
6        Keneth        Borgman  30.0          Centerline Engineering   
7          Elke      Sengbusch  36.0  Riley Riper Hollin & Colagreco   
8     Iluminada           Ohms  39.0       Nazette Marner Good Wendt   
9         Leota       Dilliard  70.0                Commercial Press   
10        Kiley      Caldarera  61.0                     Feiner Bros   
11     Veronika         Inouye  79.0                 C 4 Network Inc   
12      Rozella       Ostrosky  65.0                 Parkway Company   
13      Kanisha        Waycott  54.0             Schroer, Gene E Esq   
14      Shenika        Seewald  26.0            East Coast Marketing   
15       Kallie      Blackwood  63.0            Rowley Schlimgen Inc   
16       Bobbye           Rhym  43.0          Smits, Patricia Garity   
17      Micaela         Rhymes  75.0   H Lee Leonard Attorney At Law   
18     Dominque      Dickerson   NaN     E A I Electronic Assocs Inc   
19    Stephaine       Barfield  64.0          Beutelschies & Company   
20      Tammara        Wardrip  45.0               Jewel My Shop Inc   
21         Cory          Gibes  54.0   Chinese Translation Resources   
22       Elvera      Benimadho  20.0                 Tree Musketeers   
23        Carma      Vanheusen  20.0    Springfield Div Oh Edison Co   
24       Louisa       Cronauer  38.0  Pacific Grove Museum Ntrl Hist   
25       Shawna       Palaspas  66.0            Windsor, James L Esq   
26         Xuan         Rochin  42.0         Carol, Drake Sparks Esq   
27      Lindsey        Dilello  71.0         Biltmore Investors Bank   
28       Devora          Perez  60.0            Desco Equipment Corp   
29     Sheridan           Zane  21.0      Kentucky Tennessee Clay Co   
..          ...            ...   ...                             ...   
79     Thaddeus         Ankeny  69.0                 Atc Contracting   
80          Lai     Harabedian  80.0           Buergi & Madden Scale   
81       Lavera          Perin  36.0             Abc Enterprises Inc   
82      Arlette      Honeywell  45.0                         Smc Inc   
83      Tiffiny  Steffensmeier  37.0    Whitehall Robbins Labs Divsn   
84      Pamella      Schmierer  34.0     K Cs Cstm Mouldings Windows   
85       Lucina           Lary  40.0        Matricciani, Albert J Jr   
86      Hillary        Skulski  77.0                       Replica I   
87       Gracia         Melnyk  61.0          Juvenile & Adult Super   
88       Ashlyn        Pinilla  26.0                    Art Crafters   
89        Marge         Limmel  61.0              Bjork, Robert D Jr   
90        Avery         Steier  64.0  Dill Dill Carr & Stonbraker Pc   
91       Ressie        Auffrey   NaN                Faw, James C Cpa   
92      Lorrine         Worlds  63.0           Longo, Nicholas J Esq   
93      Martina        Staback  27.0                   Ace Signs Inc   
94        Jerry        Zurcher  65.0                    J & F Lumber   
95     Theodora       Restrepo  64.0           Kleri, Patricia S Esq   
96      Jenelle      Regusters  26.0           Haavisto, Brian F Esq   
97    Roosevelt         Hoffis  25.0                 Denbrook, Myron   
98       Denise          Patak  56.0              Spence Law Offices   
99        Audry            Yaw  29.0  Mike Uchrin Htg & Air Cond Inc   
100       Rikki          Nayar  44.0              Targan & Kievit Pa   
101         Hoa          Sarao  26.0              Kaplan, Joel S Esq   
102      Joanna     Leinenbach  72.0        Le

Q4) Delete rows with email missing.

In [4]:
#Delete rows with email missing
peopleDF.dropna(subset=['Email'])

FirstName       LastName   Age                     CompanyName  \
0        Mattie       Poquette  35.0          Century Communications   
1       Arminda         Parvis  22.0                      Newtec Inc   
2      Herminia    Nicolozakes  59.0  Sea Island Div Of Fstr Ind Inc   
3    Christiane     Eschberger  71.0              Casco Services Inc   
4        Helene    Rodenberger  30.0  Bailey Transportation Prod Inc   
5       Regenia        Kannady   NaN   Ken Jeter Store Equipment Inc   
6        Keneth        Borgman  30.0          Centerline Engineering   
7          Elke      Sengbusch  36.0  Riley Riper Hollin & Colagreco   
8     Iluminada           Ohms  39.0       Nazette Marner Good Wendt   
9         Leota       Dilliard  70.0                Commercial Press   
10        Kiley      Caldarera  61.0                     Feiner Bros   
11     Veronika         Inouye  79.0                 C 4 Network Inc   
12      Rozella       Ostrosky  65.0                 Parkway Company   
13      Kanisha        Waycott  54.0             Schroer, Gene E Esq   
14      Shenika        Seewald  26.0            East Coast Marketing   
16       Bobbye           Rhym  43.0          Smits, Patricia Garity   
17      Micaela         Rhymes  75.0   H Lee Leonard Attorney At Law   
18     Dominque      Dickerson   NaN     E A I Electronic Assocs Inc   
19    Stephaine       Barfield  64.0          Beutelschies & Company   
20      Tammara        Wardrip  45.0               Jewel My Shop Inc   
21         Cory          Gibes  54.0   Chinese Translation Resources   
22       Elvera      Benimadho  20.0                 Tree Musketeers   
23        Carma      Vanheusen  20.0    Springfield Div Oh Edison Co   
24       Louisa       Cronauer  38.0  Pacific Grove Museum Ntrl Hist   
25       Shawna       Palaspas  66.0            Windsor, James L Esq   
26         Xuan         Rochin  42.0         Carol, Drake Sparks Esq   
27      Lindsey        Dilello  71.0         Biltmore Investors Bank   
28       Devora          Perez  60.0            Desco Equipment Corp   
29     Sheridan           Zane  21.0      Kentucky Tennessee Clay Co   
30         Chau        Kitzman  49.0              Benoff, Edward Esq   
..          ...            ...   ...                             ...   
79     Thaddeus         Ankeny  69.0                 Atc Contracting   
80          Lai     Harabedian  80.0           Buergi & Madden Scale   
81       Lavera          Perin  36.0             Abc Enterprises Inc   
82      Arlette      Honeywell  45.0                         Smc Inc   
83      Tiffiny  Steffensmeier  37.0    Whitehall Robbins Labs Divsn   
84      Pamella      Schmierer  34.0     K Cs Cstm Mouldings Windows   
85       Lucina           Lary  40.0        Matricciani, Albert J Jr   
86      Hillary        Skulski  77.0                       Replica I   
87       Gracia         Melnyk  61.0          Juvenile & Adult Super   
88       Ashlyn        Pinilla  26.0                    Art Crafters   
89        Marge         Limmel  61.0              Bjork, Robert D Jr   
90        Avery         Steier  64.0  Dill Dill Carr & Stonbraker Pc   
91       Ressie        Auffrey   NaN                Faw, James C Cpa   
92      Lorrine         Worlds  63.0           Longo, Nicholas J Esq   
93      Martina        Staback  27.0                   Ace Signs Inc   
94        Jerry        Zurcher  65.0                    J & F Lumber   
95     Theodora       Restrepo  64.0           Kleri, Patricia S Esq   
96      Jenelle      Regusters  26.0           Haavisto, Brian F Esq   
97    Roosevelt         Hoffis  25.0                 Denbrook, Myron   
98       Denise          Patak  56.0              Spence Law Offices   
99        Audry            Yaw  29.0  Mike Uchrin Htg & Air Cond Inc   
100       Rikki          Nayar  44.0              Targan & Kievit Pa   
101         Hoa          Sarao  26.0              Kaplan, Joel S Esq   
102      Joanna     Leinenbach  72.0        Le

Q5) Impute the missing values in age with the mean of the column.

In [5]:
#Impute missing values for Age with mean of the column
from sklearn.impute import SimpleImputer
X=peopleDF.iloc[:,:].values
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,[2]])
X[:,[2]] =imputer.transform(X[:,[2]])

print(X[:,[2]])  # shows new age column standalone
# print(X)       # shows new age column inline with other values

[[35.0]
 [22.0]
 [59.0]
 [71.0]
 [30.0]
 [49.88235294117647]
 [30.0]
 [36.0]
 [39.0]
 [70.0]
 [61.0]
 [79.0]
 [65.0]
 [54.0]
 [26.0]
 [63.0]
 [43.0]
 [75.0]
 [49.88235294117647]
 [64.0]
 [45.0]
 [54.0]
 [20.0]
 [20.0]
 [38.0]
 [66.0]
 [42.0]
 [71.0]
 [60.0]
 [21.0]
 [49.0]
 [69.0]
 [44.0]
 [80.0]
 [49.88235294117647]
 [21.0]
 [52.0]
 [49.88235294117647]
 [80.0]
 [28.0]
 [57.0]
 [56.0]
 [43.0]
 [77.0]
 [52.0]
 [29.0]
 [51.0]
 [38.0]
 [23.0]
 [76.0]
 [75.0]
 [71.0]
 [69.0]
 [31.0]
 [32.0]
 [39.0]
 [56.0]
 [31.0]
 [56.0]
 [57.0]
 [34.0]
 [47.0]
 [44.0]
 [49.88235294117647]
 [52.0]
 [70.0]
 [23.0]
 [32.0]
 [49.0]
 [63.0]
 [27.0]
 [79.0]
 [41.0]
 [74.0]
 [26.0]
 [69.0]
 [66.0]
 [65.0]
 [41.0]
 [69.0]
 [80.0]
 [36.0]
 [45.0]
 [37.0]
 [34.0]
 [40.0]
 [77.0]
 [61.0]
 [26.0]
 [61.0]
 [64.0]
 [49.88235294117647]
 [63.0]
 [27.0]
 [65.0]
 [64.0]
 [26.0]
 [25.0]
 [56.0]
 [29.0]
 [44.0]
 [26.0]
 [72.0]
 [30.0]
 [49.0]
 [49.88235294117647]
 [42.0]
 [80.0]
 [57.0]]


Q6) Perform one hot encoding for the state column.

In [8]:
#One hot encoding for the state column
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

#Solution 1: one hot encoding for state column standalone
X=peopleDF.iloc[:,7].values
labelencoder_X = LabelEncoder()
X = labelencoder_X.fit_transform(X.astype(str))
X = X.reshape(len(X), 1)
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(X).toarray()

# Removing the extra dummy variable
X = X[:, :-1]
print(X)

#Solution 2: one hot encoding for state column inside a new dataframe
#creates 3 new columns states and NaN is 0's in each, and appened to peopleDF with concat
newDF = pd.concat([peopleDF,pd.get_dummies(peopleDF['State'], prefix='State')],axis=1)

#drops State column that is no longer needed
newDF.drop(['State'],axis=1, inplace=True)
print(newDF)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0.

C:\Users\satis\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
